import js from '@eslint/js';
import globals from 'globals';

// Lenient config, mirroring frontend/eslint.config.js: surface real problems
// without drowning an existing codebase in style noise. This runs as a hard
// gate (`--max-warnings 0`), so anything enabled here has to be worth blocking
// a merge over — style opinions belong in review, not in CI.
export default [
  {
    ignores: [
      'node_modules',
      // Generated by `prisma generate` / migrations — not ours to lint.
      'prisma/migrations',
      'src/generated',
    ],
  },
  js.configs.recommended,
  {
    files: ['**/*.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: { ...globals.node },
    },
    rules: {
      // The codebase deliberately swallows errors in best-effort paths
      // (notify, thumbnails, HLS cleanup), so an empty catch is intentional
      // here — but an empty `if`/`else`/loop body is almost always a mistake.
      'no-empty': ['error', { allowEmptyCatch: true }],

      // `_` prefix is the established opt-out. caughtErrors:'none' because
      // `catch {}` without a binding is the norm above, and a bound-but-unused
      // error in a best-effort path is not worth failing a build for.
      //
      // ignoreRestSiblings is what makes the omit idiom work: response shaping
      // is written as `const { embedding, ocrText, ...rest } = file`, where the
      // named bindings exist precisely so they are LEFT OUT of `rest`. They are
      // unused by design, and rewriting them to `_embedding` would be noise.
      'no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrors: 'none',
          ignoreRestSiblings: true,
        },
      ],

      // Real defects this codebase is exposed to, all off by default in
      // js.configs.recommended:
      //
      // Quota and byte totals mix BigInt and Number; `==` between them coerces
      // in ways that silently disagree with the `===` used elsewhere.
      eqeqeq: ['error', 'always', { null: 'ignore' }],
      //
      // Deliberately NOT enabled: `require-atomic-updates`. It flags every
      // `req.user = await …` in the auth/WebDAV middleware, which is the
      // standard Express pattern — `req` is per-request state, not shared, so
      // there is no race for it to catch. The rule targets module-level
      // variables; here it is pure false-positive noise, and the only way to
      // "fix" it would be to contort correct middleware.
      //
      // `return` inside a `finally` discards the pending exception — the temp
      // dir cleanup in youtube.service.js is exactly this shape.
      'no-unsafe-finally': 'error',
      // Silently drops a promise rejection into an unhandled rejection.
      'no-async-promise-executor': 'error',
      // Reassigning a function parameter that is also destructured reads as a
      // mutation of the caller's object.
      'no-param-reassign': ['error', { props: false }],
    },
  },
  {
    // Tests use vitest's explicit imports (no `globals: true` in the vitest
    // configs), so no test globals are needed — but they do reach for process
    // env and console more freely.
    files: ['test/**/*.js', 'scripts/**/*.js', '*.config.js'],
    rules: {
      'no-console': 'off',
    },
  },
];
